{"uuid": "c5571e7d-70fe-40e3-bd9b-086d01421587", "children": ["6b0883d2-34f6-4dc4-8c14-b812bcc498a5"], "befores": [{"name": "_xunit_setup_class_fixture_TestAddGoods", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 787, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 715, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\Desktop\\黑马\\第二章 Linux和MySQL数据库\\UI_Auto_Tphop\\script\\admin_script\\test_goods.py\", line 21, in setup_class\n    self.driver = DriverUtils.get_admin_driver()\n  File \"D:\\Desktop\\黑马\\第二章 Linux和MySQL数据库\\UI_Auto_Tphop\\utils.py\", line 53, in get_admin_driver\n    cls.__admin_driver = selenium.webdriver.Chrome()\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 50, in __init__\n    if finder.get_browser_path():\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 47, in get_browser_path\n    return self._binary_paths()[\"browser_path\"]\n  File \"D:\\Coder2\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 78, in _binary_paths\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1747795460512, "stop": 1747795461875}], "start": 1747795460512, "stop": 1747795462056}